/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyTotalView = IDL.Record({
  'date' : IDL.Text,
  'productQuantities' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalRevenue' : IDL.Nat64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'billPrintLocation' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllDailyTotals' : IDL.Func([], [], []),
  'getBalanceSheet' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, DailyTotalView))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTotal' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(DailyTotalView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyTotal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat64, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyTotalView = IDL.Record({
    'date' : IDL.Text,
    'productQuantities' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalRevenue' : IDL.Nat64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'billPrintLocation' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllDailyTotals' : IDL.Func([], [], []),
    'getBalanceSheet' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, DailyTotalView))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTotal' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(DailyTotalView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyTotal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat64, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };